### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by hypervillain** [sw-yx/netlify-plugin-search-index#2]
👋Hey,

I came across this repository while working on a new version of my pet project [TryCereals](https://trycereals.com), which generates production-ready JSX and then commits it to Git. Adding build plugins there would be an awesome next step.

Anyway, I'd be super happy to become a maintainer of this plugin! This would also be my first OS contribution, so I'd still hope for some guidance from you guys.

After reading a bit of code, I think I could start with implementing Fuse's weighted search by parsing the HTML file and sorting its content (meta tags, Hs, then text, etc.). Does it sound like something you would like to do?

Happy to talk further,
Hugo

**Comment by swyxio** [comment]
hey! yup! feel free to. adding you now

**Comment by swyxio** [comment]
if you let me know your npm name i can also give you publish rights
