### ISSUE TITLE
Post Customization

### ISSUE THREAD

**Issue by AylanBoscarino** [sw-yx/netlify-plugin-search-index#30]
**Is your feature request related to a problem? Please describe.**
This plugin is great but it would be even better if the user can chose the fields of the post that will be indexed and retrieved. 

**Describe the solution you'd like**
The ideal scenario would be possible for the user to pass an optional array with the field names in the `netlify.toml` configuration of the plugin.

**Describe alternatives you've considered**
To enable customizations via Netlify Functions

**Comment by swyxio** [comment]
PR welcome!

**Comment by swyxio** [comment]
also if you woul like to take over maintenance lmk
