### ISSUE TITLE
Deployment fails with error Error: FUNCTIONS_SRC is undefined

### ISSUE THREAD

**Issue by bobsingor** [sw-yx/netlify-plugin-search-index#7]
**Describe the bug**
Deployment gives me the following error: Error: FUNCTIONS_SRC is undefined - did you forget to declare a functions folder in netlify.toml

I can't find anything about functions_src inside your documentation. Am I missing something? Please let me know

**Comment by swyxio** [comment]
hey! yeah as the error says you should declare a functions folder in `netlify.toml`

example https://github.com/sw-yx/netlify-plugin-search-index/blob/master/netlify.toml#L4

docs https://docs.netlify.com/configure-builds/file-based-configuration/#functions

**Comment by ehmicky** [comment]
This should be fixed by #8.
